### ISSUE TITLE
Determine the concentration

### ISSUE THREAD

**Issue by luis2812** [bryanhanson/ChemoSpec#24] opened 2019-08-03 19:47 UTC
I want to determine the concentration of the substance into the matrix. How do I built a calibration curve to determine the concentration?

**Comment by bryanhanson** [comment] 2019-08-03 20:11
Hi Luis...

1. What kind of spectra do you have?
2. Have you imported your spectra in ChemoSpec?
3. If yes to #2, do you have both the calibration spectra and the samples for which you need the concentration in the Spectra object?

Bryan

**Comment by luis2812** [comment] 2019-08-09 04:29
Hi, greetings!

I have doubts about to set up the calibration curve. I've read some papers,
where the curve of calibration is  treated by PLS (partial least squares)
but in the packing ChemoSpec I didn't see this function.

I want determine the concentration of ácid salicylic in a mixture of other
ingredients.

I hope you can help me with this.

Very thanks!

**Comment by bryanhanson** [comment] 2019-08-09 12:36
Hi Luis... You are correct, `ChemoSpec` does not do pls.  That's because there is an excellent package called `pls` which can do not only pls but also pcr, which might be better for spectroscopic applications if all you need is a predictive model.  pls has a vignette available:

```
install.packages("pls")
library("pls")
browseVignettes("pls")
```
If you decide to do pls, the input data you need is in your Spectra object, specifically  it's in `spectra$data`.  All you have to do is add your response vector.  If you want to do pcr, run for example `pca <- c_pcaSpectra(...)` and the scores will be in `pca$x`.  Again, you would add your response vector.  Once you have data + response vector, the pls package can make your models in a very straightforward manner.

**Comment by luis2812** [comment] 2019-08-09 15:37
Hi, good morning!

So thanks!  Then, Can I work with ChemoSpect and pls packages at same time?
I have a doubt, Is the concentration of drug the response vector? and How
can I calculate the concentration of sample after with the prediction model?

I´m going to read more about this.   I appreciate  your help because it
will uselful in order to get my goals.

**Comment by bryanhanson** [comment] 2019-08-09 15:58
Yes, for your calibration curve the known drug concentrations would be the response vector (y value) and either the raw data or the reduced raw data (pca results) would be your x values.  `pls` will give you an equation after the fit from which you can compute unknown drug concentrations.  
The resulting model will likely be easiest to understand if you use pca and keep only  a few of the principal components.  Then it's a very straightforward case of multiple regression, and you'll have to select your predictive variables that work best for your system.  Check out the `pls` vignette and the paper referenced in it.

And yes, `pls` and `ChemoSpec` can work together just fine.

**Closed** 2020-01-19 19:09 UTC
